# Generated by Django 5.0.6 on 2024-06-19 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranimefavorites',
            unique_together={('idUsuario', 'idAnime')},
        ),
    ]
