# Generated by Django 5.0.6 on 2024-06-17 05:15

import tienda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='img_route',
            field=models.ImageField(blank=True, null=True, upload_to=tienda.models.get_upload_to),
        ),
        migrations.AlterModelTable(
            name='animecategories',
            table='AnimeCategories',
        ),
    ]
