# Generated by Django 5.0.6 on 2024-06-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='img_route',
            field=models.CharField(max_length=200),
        ),
    ]
