# Generated by Django 5.0.6 on 2024-06-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_anime_img_route_alter_animecategories_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='img_route',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
