# Generated by Django 5.0.6 on 2024-06-17 05:37

import tienda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_anime_img_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='img_route',
            field=models.ImageField(blank=True, null=True, upload_to=tienda.models.get_upload_to),
        ),
    ]
